version: 2.1
jobs:
  saving:
    docker:
      - image: cypress/base:14.15.0
    steps:
      - run: id
      - run: mkdir test
      - run: echo data > test/file.txt
      - run: chown -R 3434:3434 /root
      - run: ls -la /root
      - save_cache:
          paths:
            - test
            - not-real
          key: server-dependencies-v1-3

  restoring:
    docker:
      - image: cimg/node:14.15.1
    steps:
      - run: id
      - restore_cache:
          keys:
            - server-dependencies-v1-3
      - run: ls -la

workflows:
  do_cache:
    jobs:
      - saving
      - restoring:
          requires:
            - saving