version: 2.1
jobs:
  saving:
    docker:
      - image: cypress/base:14.15.0
    steps:
      - run: mkdir test
      - run: echo data > test/file.txt
      - save_cache:
          paths:
            - test
            - not-real
          key: server-dependencies-v1-1

  restoring:
    docker:
      - image: cimg/node:14.15.1
    steps:
      - restore_cache:
          keys:
            - server-dependencies-v1-1
      - run: ls -la

workflows:
  do_cache:
    jobs:
      - saving
      - restoring