version: 2
jobs:
  build:
    docker:
      - image: "alpine:latest"
        command: ['/bin/sh', '-c', "exit 1"]
    steps:
      - run:
          name: sample name
          command: echo -n he; echo llo there
