version: 2.1
jobs:
  saving:
    docker:
      - image: cypress/base:14.15.0
    steps:
      - run: id
      - run: mkdir -p /root/test
      - run: echo data > /root/file.txt
      - save_cache:
          paths:
            - /root/test
            - not-real
          key: server-dependencies-v1-6

  restoring:
    docker:
      - image: cimg/node:14.15.1
    steps:
      - run: id
      - restore_cache:
          keys:
            - server-dependencies-v1-6
      - run: ls -la

workflows:
  do_cache:
    jobs:
      - saving
      - restoring:
          requires:
            - saving